  const questions = [
  // --- MOBS & CREATURES ---
  { question: "What special rainbow effect happens when you name a sheep 'jeb_' using a name tag?", answer: "The sheep's wool continuously cycles through all rainbow colors!" },
  { question: "Which mob drops Ender Pearls when defeated?", answer: "Enderman." },
  { question: "What happens when you name a rabbit 'Toast' using a name tag?", answer: "It changes its skin to a black-and-white memorial skin." },
  { question: "Which neutral mob can be tamed using Bones?", answer: "The Wolf." },
  { question: "What food item do you use to tame and breed Cats?", answer: "Raw Cod or Raw Salmon." },
  { question: "Which passive mob turns upside down when named 'Dinnerbone' or 'Grumm'?", answer: "Any mob in the game!" },
  { question: "What hostile mob burns in daylight unless standing in water or shade?", answer: "Zombies and Skeletons." },
  { question: "What flying hostile mob spawns in the Nether and shoots fireballs?", answer: "Ghast." },
  { question: "What neutral mob transforms into a Zombified Piglin when brought to the Overworld?", answer: "Piglin." },
  { question: "What aggressive sea creature drops Prismarine Shards?", answer: "Guardian (and Elder Guardian)." },
  { question: "What mob drops Slimeballs when killed?", answer: "Slime." },
  { question: "What passive mob produces Milk when right-clicked with a Bucket?", answer: "Cow (and Mooshroom)." },
  { question: "What special item can you get by shearing a Mooshroom?", answer: "Red Mushrooms (it turns into a regular cow)." },
  { question: "Which passive mob drops Feathers and Raw Chicken?", answer: "Chicken." },
  { question: "What item do you feed Turtles to make them breed?", answer: "Seagrass." },
  { question: "Which rare underwater mob can regenerate its health and pick up items?", answer: "Axolotl." },
  { question: "What mob shoots levitation bullets that make you float into the air?", answer: "Shulker." },
  { question: "Which hostile mob attacks players who haven't slept for 3 in-game days?", answer: "Phantom." },
  { question: "What friendly mob dances when a Music Disc is played nearby in a Jukebox?", answer: "Parrot." },
  { question: "What aquatic mob drops Nautilus Shells occasionally upon death?", answer: "Drowned." },
  { question: "What mob is afraid of Creepers?", answer: "Cats and Ocelots." },
  { question: "What mob inflicts the Poison status effect when attacking in caves?", answer: "Cave Spider." },
  { question: "Which Nether mob drops Blaze Rods?", answer: "Blaze." },
  { question: "What mob spawns from Monster Spawners in Nether Fortresses?", answer: "Blaze." },
  { question: "What neutral mob attacks in packs if you touch their babies in icy biomes?", answer: "Polar Bear." },
  { question: "What mob drops Leather and Raw Beef?", answer: "Cow." },
  { question: "What passive animal carries chests to store extra inventory items?", answer: "Llama / Donkey / Mule." },
  { question: "What mob drops String and Spider Eyes?", answer: "Spider." },
  { question: "What hostile mob charges at players with an axe during a Raid?", answer: "Vindicator." },
  { question: "Which boss mob emits a sonic boom attack from its chest in Deep Dark biomes?", answer: "The Warden." },

  // --- MINING, ORES & BLOCKS ---
  { question: "What tool is required to mine Diamond Ore?", answer: "An Iron Pickaxe or better." },
  { question: "What block is created when running water flows over lava source blocks?", answer: "Obsidian." },
  { question: "What rare ore is found in the Nether and used to craft Netherite Ingots?", answer: "Ancient Debris." },
  { question: "How many Obsidian blocks are required at minimum to build a Nether Portal?", answer: "10 blocks." },
  { question: "Name a block affected by gravity.", answer: "Sand, Gravel, Anvil, Dragon Egg, or Concrete Powder." },
  { question: "Which light-emitting block is crafted from Prismarine Shards and Crystals?", answer: "Sea Lantern." },
  { question: "What block causes players and mobs to walk significantly slower?", answer: "Soul Sand (or Honey Block)." },
  { question: "What block is mined to get Redstone Dust?", answer: "Redstone Ore." },
  { question: "Which ore must be smelted in a Furnace to yield copper ingots?", answer: "Raw Copper (or Copper Ore)." },
  { question: "What block prevents fall damage entirely when landed on?", answer: "Water source block / Slime Block / Hay Bale (reduces 80%)." },
  { question: "What block can be used to set a spawn point in the Nether?", answer: "Respawn Anchor." },
  { question: "What block glows red and powers adjacent redstone components when clicked?", answer: "Redstone Torch / Lever / Button." },
  { question: "What item is mined from Quartz Ore in the Nether?", answer: "Nether Quartz." },
  { question: "What block drops Flint when destroyed without Silk Touch?", answer: "Gravel." },
  { question: "Which block requires Silk Touch to be harvested as itself without breaking?", answer: "Glass / Ice / Glowstone / Ore blocks." },
  { question: "What block is made from 9 Wheat items?", answer: "Hay Bale." },
  { question: "What block is created when water touches lava flowing blocks?", answer: "Cobblestone." },
  { question: "What block is mined in End Cities to store items across dimensions?", answer: "Ender Chest." },
  { question: "What block is crafted using 4 Glowstone Dust?", answer: "Glowstone." },
  { question: "What block reduces light level and is crafted using Honeycombs?", answer: "Candle." },

  // --- CRAFTING & ITEMS ---
  { question: "How do you craft an Enchanting Table?", answer: "1 Book, 2 Diamonds, and 4 Obsidian." },
  { question: "What item is crafted using 3 Wheat in a horizontal row?", answer: "Bread." },
  { question: "What item allows players to glide through the air?", answer: "Elytra." },
  { question: "What tool is used to shear wool from sheep?", answer: "Shears." },
  { question: "What ingredient is needed alongside Gold Ingots to upgrade Diamond gear?", answer: "Netherite Upgrade Template & Netherite Ingot." },
  { question: "How many iron ingots are required to craft a Bucket?", answer: "3 Iron Ingots." },
  { question: "What item is crafted with 1 Stick and 1 Coal/Charcoal?", answer: "4 Torches." },
  { question: "How many Iron Ingots does it take to craft an Anvil?", answer: "3 Iron Blocks + 4 Iron Ingots (31 total)." },
  { question: "What item is used to lead animals around?", answer: "Lead (crafted with String and Slimeball)." },
  { question: "What item is crafted using 8 Cobblestone around a blank center space?", answer: "Furnace." },
  { question: "What ingredient is needed to craft a Clock alongside Gold Ingots?", answer: "Redstone Dust." },
  { question: "What tool is needed to collect ice blocks without melting them?", answer: "Tool with Silk Touch." },
  { question: "What item allows you to record coordinates and map terrain?", answer: "Map." },
  { question: "How many Diamond blocks do you need to craft a Diamond Pickaxe?", answer: "0 blocks (it takes 3 Diamonds)." },
  { question: "What item can be launched from a Crossbow to create explosive fireworks?", answer: "Firework Rocket." },
  { question: "What item removes all status effects when consumed?", answer: "Milk Bucket." },
  { question: "What item drops when breaking tall grass?", answer: "Seeds." },
  { question: "How many slots does a single Chest contain?", answer: "27 slots." },
  { question: "What item is crafted with 3 Sticks and 2 String?", answer: "Fishing Rod." },
  { question: "What item is crafted with 3 Iron Ingots and 2 Sticks?", answer: "Iron Pickaxe." },

  // --- BREWING & ENCHANTS ---
  { question: "What item do you need to brew a Potion of Swiftness?", answer: "Sugar (added to Awkward Potion)." },
  { question: "What basic item is required as fuel in a Brewing Stand?", answer: "Blaze Powder." },
  { question: "What ingredient extends the duration of a potion?", answer: "Redstone Dust." },
  { question: "What ingredient increases the tier level (Strength II) of a potion?", answer: "Glowstone Dust." },
  { question: "What item turns a potion into a Splash Potion?", answer: "Gunpowder." },
  { question: "What ingredient is added to turn a Splash Potion into a Lingering Potion?", answer: "Dragon's Breath." },
  { question: "Which enchantment allows you to walk on water by freezing it?", answer: "Frost Walker." },
  { question: "Which enchantment prevents items from dropping on death by destroying them?", answer: "Curse of Vanishing." },
  { question: "Which enchantment automatically repairs tools using XP Orbs?", answer: "Mending." },
  { question: "Which enchantment increases the amount of loot dropped by mobs?", answer: "Looting." },
  { question: "Which enchantment increases the yield of mined ores?", answer: "Fortune." },
  { question: "Which enchantment allows underwater breathing for longer durations?", answer: "Respiration." },
  { question: "What ingredient turns an Awkward Potion into a Potion of Healing?", answer: "Glistering Melon Slice." },
  { question: "What potion ingredient is dropped by Magma Cubes?", answer: "Magma Cream." },
  { question: "Which enchantment propels the player forward when using a Trident in water or rain?", answer: "Riptide." },

  // --- GAMEPLAY & DIMENSIONS ---
  { question: "What happens if you sleep in a bed in the Nether or the End?", answer: "The bed explodes!" },
  { question: "What item is required to activate an End Portal frame?", answer: "Eye of Ender." },
  { question: "What effect is granted by eating a Golden Apple?", answer: "Absorption and Regeneration." },
  { question: "What weather event enables Channeling on a Trident to strike lightning?", answer: "Thunderstorm." },
  { question: "What boss is summoned using Soul Sand and 3 Wither Skeleton Skulls?", answer: "The Wither." },
  { question: "What item drops from the Ender Dragon upon its first defeat?", answer: "Dragon Egg." },
  { question: "What height layer (Y level) in original Minecraft was bedrock historically found at?", answer: "Y = 0." },
  { question: "What structure in the Overworld contains Monster Spawners and Chests buried underground?", answer: "Dungeon." },
  { question: "What structure spawns in oceans and holds sponges and Elder Guardians?", answer: "Ocean Monument." },
  { question: "What rare structure generated in Dark Forests contains Evokers and Allays?", answer: "Woodland Mansion." },
  { question: "How many eyes are required to fill a complete End Portal frame?", answer: "12 Eyes of Ender." },
  { question: "What status effect do Bad Omen potions trigger upon entering a village?", answer: "A Raid." },
  { question: "What color is the beacon beam by default when no stained glass is placed above it?", answer: "White." },
  { question: "What happens to a pig when struck by lightning?", answer: "It turns into a Zombified Piglin." },
  { question: "What structure found in desert biomes contains hidden TNT traps under pressure plates?", answer: "Desert Temple." },
  { question: "What item allows players to set a custom respawn location in the Nether?", answer: "Respawn Anchor." },
  { question: "What is the maximum stack size for most items in Minecraft?", answer: "64." },
  { question: "What is the maximum stack size for Ender Pearls, Eggs, and Snowballs?", answer: "16." },
  { question: "What item cannot be stacked at all in inventory slots?", answer: "Tools, Armor, Weapons, Boats, Minecarts, Beds, and Potions." },
  { question: "Who is the original creator of Minecraft?", answer: "Markus 'Notch' Persson." }
];
