  const questions = [
  // --- MOBS & CREATURES ---
  { question: "What special rainbow effect happens when you name a sheep 'jeb_' using a name tag?", answer: "The sheep's wool continuously cycles through all rainbow colors!" },
  { question: "Which mob drops Ender Pearls when defeated?", answer: "Enderman." },
  { question: "What happens when you name a rabbit 'Toast' using a name tag?", answer: "It changes its skin to a black-and-white memorial skin." },
  { question: "Which neutral mob can be tamed using Bones?", answer: "The Wolf." },
  { question: "What food item do you use to tame and breed Cats?", answer: "Raw Cod or Raw Salmon." },
  { question: "Which passive mob turns upside down when named 'Dinnerbone' or 'Grumm'?", answer: "Any mob in the game!" },
  { question: "What hostile mob burns in daylight unless standing in water or shade?", answer: "Zombies and Skeletons." },
  { question: "What flying hostile mob spawns in the Nether and shoots fireballs?", answer: "Ghast." },
  { question: "What neutral mob transforms into a Zombified Piglin when brought to the Overworld?", answer: "Piglin." },
  { question: "What aggressive sea creature drops Prismarine Shards?", answer: "Guardian (and Elder Guardian)." },
  { question: "What mob drops Slimeballs when killed?", answer: "Slime." },
  { question: "What passive mob produces Milk when right-clicked with a Bucket?", answer: "Cow (and Mooshroom)." },
  { question: "What special item can you get by shearing a Mooshroom?", answer: "Red Mushrooms (it turns into a regular cow)." },
  { question: "Which passive mob drops Feathers and Raw Chicken?", answer: "Chicken." },
  { question: "What item do you feed Turtles to make them breed?", answer: "Seagrass." },
  { question: "Which rare underwater mob can regenerate its health and pick up items?", answer: "Axolotl." },
  { question: "What mob shoots levitation bullets that make you float into the air?", answer: "Shulker." },
  { question: "Which hostile mob attacks players who haven't slept for 3 in-game days?", answer: "Phantom." },
  { question: "What friendly mob dances when a Music Disc is played nearby in a Jukebox?", answer: "Parrot." },
  { question: "What aquatic mob drops Nautilus Shells occasionally upon death?", answer: "Drowned." },
  { question: "What mob is afraid of Creepers?", answer: "Cats and Ocelots." },
  { question: "What mob inflicts the Poison status effect when attacking in caves?", answer: "Cave Spider." },
  { question: "Which Nether mob drops Blaze Rods?", answer: "Blaze." },
  { question: "What mob spawns from Monster Spawners in Nether Fortresses?", answer: "Blaze." },
  { question: "What neutral mob attacks in packs if you touch their babies in icy biomes?", answer: "Polar Bear." },
  { question: "What mob drops Leather and Raw Beef?", answer: "Cow." },
  { question: "What passive animal carries chests to store extra inventory items?", answer: "Llama / Donkey / Mule." },
  { question: "What mob drops String and Spider Eyes?", answer: "Spider." },
  { question: "What hostile mob charges at players with an axe during a Raid?", answer: "Vindicator." },
  { question: "Which boss mob emits a sonic boom attack from its chest in Deep Dark biomes?", answer: "The Warden." },

  // --- MINING, ORES & BLOCKS ---
  { question: "What tool is required to mine Diamond Ore?", answer: "An Iron Pickaxe or better." },
  { question: "What block is created when running water flows over lava source blocks?", answer: "Obsidian." },
  { question: "What rare ore is found in the Nether and used to craft Netherite Ingots?", answer: "Ancient Debris." },
  { question: "How many Obsidian blocks are required at minimum to build a Nether Portal?", answer: "10 blocks." },
  { question: "Name a block affected by gravity.", answer: "Sand, Gravel, Anvil, Dragon Egg, or Concrete Powder." },
  { question: "Which light-emitting block is crafted from Prismarine Shards and Crystals?", answer: "Sea Lantern." },
  { question: "What block causes players and mobs to walk significantly slower?", answer: "Soul Sand (or Honey Block)." },
  { question: "What block is mined to get Redstone Dust?", answer: "Redstone Ore." },
  { question: "Which ore must be smelted in a Furnace to yield copper ingots?", answer: "Raw Copper (or Copper Ore)." },
  { question: "What block prevents fall damage entirely when landed on?", answer: "Water source block / Slime Block / Hay Bale (reduces 80%)." },
  { question: "What block can be used to set a spawn point in the Nether?", answer: "Respawn Anchor." },
  { question: "What block glows red and powers adjacent redstone components when clicked?", answer: "Redstone Torch / Lever / Button." },
  { question: "What item is mined from Quartz Ore in the Nether?", answer: "Nether Quartz." },
  { question: "What block drops Flint when destroyed without Silk Touch?", answer: "Gravel." },
  { question: "Which block requires Silk Touch to be harvested as itself without breaking?", answer: "Glass / Ice / Glowstone / Ore blocks." },
  { question: "What block is made from 9 Wheat items?", answer: "Hay Bale." },
  { question: "What block is created when water touches lava flowing blocks?", answer: "Cobblestone." },
  { question: "What block is mined in End Cities to store items across dimensions?", answer: "Ender Chest." },
  { question: "What block is crafted using 4 Glowstone Dust?", answer: "Glowstone." },
  { question: "What block reduces light level and is crafted using Honeycombs?", answer: "Candle." },

  // --- CRAFTING & ITEMS ---
  { question: "How do you craft an Enchanting Table?", answer: "1 Book, 2 Diamonds, and 4 Obsidian." },
  { question: "What item is crafted using 3 Wheat in a horizontal row?", answer: "Bread." },
  { question: "What item allows players to glide through the air?", answer: "Elytra." },
  { question: "What tool is used to shear wool from sheep?", answer: "Shears." },
  { question: "What ingredient is needed alongside Gold Ingots to upgrade Diamond gear?", answer: "Netherite Upgrade Template & Netherite Ingot." },
  { question: "How many iron ingots are required to craft a Bucket?", answer: "3 Iron Ingots." },
  { question: "What item is crafted with 1 Stick and 1 Coal/Charcoal?", answer: "4 Torches." },
  { question: "How many Iron Ingots does it take to craft an Anvil?", answer: "3 Iron Blocks + 4 Iron Ingots (31 total)." },
  { question: "What item is used to lead animals around?", answer: "Lead (crafted with String and Slimeball)." },
  { question: "What item is crafted using 8 Cobblestone around a blank center space?", answer: "Furnace." },
  { question: "What ingredient is needed to craft a Clock alongside Gold Ingots?", answer: "Redstone Dust." },
  { question: "What tool is needed to collect ice blocks without melting them?", answer: "Tool with Silk Touch." },
  { question: "What item allows you to record coordinates and map terrain?", answer: "Map." },
  { question: "How many Diamond blocks do you need to craft a Diamond Pickaxe?", answer: "0 blocks (it takes 3 Diamonds)." },
  { question: "What item can be launched from a Crossbow to create explosive fireworks?", answer: "Firework Rocket." },
  { question: "What item removes all status effects when consumed?", answer: "Milk Bucket." },
  { question: "What item drops when breaking tall grass?", answer: "Seeds." },
  { question: "How many slots does a single Chest contain?", answer: "27 slots." },
  { question: "What item is crafted with 3 Sticks and 2 String?", answer: "Fishing Rod." },
  { question: "What item is crafted with 3 Iron Ingots and 2 Sticks?", answer: "Iron Pickaxe." },

  // --- BREWING & ENCHANTS ---
  { question: "What item do you need to brew a Potion of Swiftness?", answer: "Sugar (added to Awkward Potion)." },
  { question: "What basic item is required as fuel in a Brewing Stand?", answer: "Blaze Powder." },
  { question: "What ingredient extends the duration of a potion?", answer: "Redstone Dust." },
  { question: "What ingredient increases the tier level (Strength II) of a potion?", answer: "Glowstone Dust." },
  { question: "What item turns a potion into a Splash Potion?", answer: "Gunpowder." },
  { question: "What ingredient is added to turn a Splash Potion into a Lingering Potion?", answer: "Dragon's Breath." },
  { question: "Which enchantment allows you to walk on water by freezing it?", answer: "Frost Walker." },
  { question: "Which enchantment prevents items from dropping on death by destroying them?", answer: "Curse of Vanishing." },
  { question: "Which enchantment automatically repairs tools using XP Orbs?", answer: "Mending." },
  { question: "Which enchantment increases the amount of loot dropped by mobs?", answer: "Looting." },
  { question: "Which enchantment increases the yield of mined ores?", answer: "Fortune." },
  { question: "Which enchantment allows underwater breathing for longer durations?", answer: "Respiration." },
  { question: "What ingredient turns an Awkward Potion into a Potion of Healing?", answer: "Glistering Melon Slice." },
  { question: "What potion ingredient is dropped by Magma Cubes?", answer: "Magma Cream." },
  { question: "Which enchantment propels the player forward when using a Trident in water or rain?", answer: "Riptide." },

  // --- GAMEPLAY & DIMENSIONS ---
  { question: "What happens if you sleep in a bed in the Nether or the End?", answer: "The bed explodes!" },
  { question: "What item is required to activate an End Portal frame?", answer: "Eye of Ender." },
  { question: "What effect is granted by eating a Golden Apple?", answer: "Absorption and Regeneration." },
  { question: "What weather event enables Channeling on a Trident to strike lightning?", answer: "Thunderstorm." },
  { question: "What boss is summoned using Soul Sand and 3 Wither Skeleton Skulls?", answer: "The Wither." },
  { question: "What item drops from the Ender Dragon upon its first defeat?", answer: "Dragon Egg." },
  { question: "What height layer (Y level) in original Minecraft was bedrock historically found at?", answer: "Y = 0." },
  { question: "What structure in the Overworld contains Monster Spawners and Chests buried underground?", answer: "Dungeon." },
  { question: "What structure spawns in oceans and holds sponges and Elder Guardians?", answer: "Ocean Monument." },
  { question: "What rare structure generated in Dark Forests contains Evokers and Allays?", answer: "Woodland Mansion." },
  { question: "How many eyes are required to fill a complete End Portal frame?", answer: "12 Eyes of Ender." },
  { question: "What status effect do Bad Omen potions trigger upon entering a village?", answer: "A Raid." },
  { question: "What color is the beacon beam by default when no stained glass is placed above it?", answer: "White." },
  { question: "What happens to a pig when struck by lightning?", answer: "It turns into a Zombified Piglin." },
  { question: "What structure found in desert biomes contains hidden TNT traps under pressure plates?", answer: "Desert Temple." },
  { question: "What item allows players to set a custom respawn location in the Nether?", answer: "Respawn Anchor." },
  { question: "What is the maximum stack size for most items in Minecraft?", answer: "64." },
  { question: "What is the maximum stack size for Ender Pearls, Eggs, and Snowballs?", answer: "16." },
  { question: "What item cannot be stacked at all in inventory slots?", answer: "Tools, Armor, Weapons, Boats, Minecarts, Beds, and Potions." },
  { question: "Who is the original creator of Minecraft?", answer: "Markus 'Notch' Persson." }

    // --- REDSTONE & MECHANICS ---
  { question: "What redstone component delays a signal and prevents backflow?", answer: "Redstone Repeater." },
  { question: "What component compares redstone signals or measures container fullness?", answer: "Redstone Comparator." },
  { question: "What block outputs a redstone signal when it detects a block update in front of it?", answer: "Observer." },
  { question: "What block pushes blocks away when powered by redstone?", answer: "Piston." },
  { question: "What block pushes AND pulls blocks back when powered by redstone?", answer: "Sticky Piston." },
  { question: "What block pulls items into its inventory and passes them to attached containers?", answer: "Hopper." },
  { question: "What block shoots items out into the world when powered by redstone?", answer: "Dropper (or Dispenser)." },
  { question: "What item-firing block can equip armor onto players or fire arrows?", answer: "Dispenser." },
  { question: "What block emits light and power based on the sun or moon's position?", answer: "Daylight Detector." },
  { question: "What redstone component is crafted using 3 Stone, 2 Redstone Torches, and 1 Quartz?", answer: "Redstone Repeater." },
  { question: "What block sticks to other blocks when moved by pistons, lifting entities above it?", answer: "Slime Block (or Honey Block)." },
  { question: "Do Slime Blocks and Honey Blocks stick to each other when moved together?", answer: "No, they slide past each other!" },
  { question: "What block can pistons NEVER push or break?", answer: "Bedrock (or Obsidian / Crying Obsidian / Ancient Debris)." },
  { question: "What ingredient is used to craft Redstone Torches?", answer: "1 Stick and 1 Redstone Dust." },
  { question: "What redstone signal strength is emitted by a Target block when hit in the exact center?", answer: "Signal strength 15." },

  // --- WEAPONS, ARMOR & TOOLS ---
  { question: "What ranged weapon uses Firework Rockets or Arrows as ammo?", answer: "Crossbow." },
  { question: "What weapon can be thrown and retrieved using the Loyalty enchantment?", answer: "Trident." },
  { question: "What armor tier is crafted using Leather items?", answer: "Leather Armor." },
  { question: "What armor piece protects a horse from damage?", answer: "Horse Armor." },
  { question: "What tool is used to carve faces into Pumpkins?", answer: "Shears." },
  { question: "What item is used to repair elytra on an anvil?", answer: "Phantom Membrane." },
  { question: "What material makes Gold armor special around Piglins?", answer: "It prevents Piglins from becoming aggressive!" },
  { question: "What tool converts Grass Blocks into Dirt Paths?", answer: "Shovel." },
  { question: "What tool converts Wood Logs into Stripped Logs?", answer: "Axe." },
  { question: "What tool is used to tilt or rotate Redstone components in creative mode?", answer: "Debug Stick." },
  { question: "What weapon deals increased damage when dropped from height onto an enemy?", answer: "Mace." },
  { question: "What item is dropped by Breeze mobs and used to craft the Mace?", answer: "Breeze Rod." },
  { question: "What weapon enchantment increases damage specifically against undead mobs like Zombies?", answer: "Smite." },
  { question: "What weapon enchantment increases damage against arthropods like Spiders and Silverfish?", answer: "Bane of Arthropods." },
  { question: "What enchantment sets targets on fire when hit with a sword?", answer: "Fire Aspect." },

  // --- FOOD, FARMING & FISHING ---
  { question: "What crop requires water nearby and produces Seeds when harvested?", answer: "Wheat." },
  { question: "What farmable root vegetable can turn into a Poisonous variant when harvested?", answer: "Potato." },
  { question: "What food item is crafted by combining Sugar, Milk, Eggs, and Wheat?", answer: "Cake." },
  { question: "What farming item can be grown attached to stems on farmland?", answer: "Pumpkin (or Melon)." },
  { question: "What golden food item is crafted with a Carrot and 8 Gold Nuggets?", answer: "Golden Carrot." },
  { question: "What food item restores hunger and grants Fire Resistance when crafted as a Stew?", answer: "Suspicious Stew." },
  { question: "What plant grows vertically in ocean biomes and can be dried in a furnace?", answer: "Kelp." },
  { question: "What block accelerates crop growth when filled with Bone Meal?", answer: "Composter." },
  { question: "What item do you feed Axolotls to breed them?", answer: "Tropical Fish Bucket." },
  { question: "What item do you feed Bees to breed them?", answer: "Any Flower." },
  { question: "What item do you feed Frogs to breed them?", answer: "Slimeball." },
  { question: "What crop grows directly on Sniffer-dug Torchflower Seeds?", answer: "Torchflower." },
  { question: "What item do Pandas eat and breed with?", answer: "Bamboo." },
  { question: "What item do Striders eat to follow players?", answer: "Warped Fungus on a Stick." },
  { question: "What food item is obtained by fishing or killing Salmon?", answer: "Raw Salmon." },

  // --- NETHER & END DIMENSIONS ---
  { question: "What Nether structure is made of Nether Bricks and guarded by Blazes?", answer: "Nether Fortress." },
  { question: "What large Nether structure is home to Piglins and holds Gold Treasures?", answer: "Bastion Remnant." },
  { question: "What plant grows on Soul Sand in the Nether and is used in brewing?", answer: "Nether Wart." },
  { question: "What blue wood-like tree grows in the Nether's Warped Forests?", answer: "Warped Hyphae / Stem." },
  { question: "What red wood-like tree grows in Crimson Forests?", answer: "Crimson Hyphae / Stem." },
  { question: "What floating purple city generates on outer End islands?", answer: "End City." },
  { question: "What plant grows in the End and yields Chorus Fruit when broken?", answer: "Chorus Plant." },
  { question: "What item teleports players randomly when eaten?", answer: "Chorus Fruit." },
  { question: "What crystals heal the Ender Dragon during battle?", answer: "End Crystals." },
  { question: "What block destroys End Crystals when hit with arrows or melee attacks?", answer: "Bedrock pillars / Glass cages." },
  { question: "What particle effect fills the air in the Nether's Basalt Deltas?", answer: "White Ash particles." },
  { question: "What hostile Nether mob floats in lava and can be ridden with a saddle?", answer: "Strider." },
  { question: "What item pacifies Piglins so they trade with you instead of attacking?", answer: "Gold Ingot." },
  { question: "What mob transforms into a Zoglin when brought out of the Nether?", answer: "Hoglin." },
  { question: "What Nether block burns infinitely without extinguishing?", answer: "Netherrack." },

  // --- STRUCTURES & BIOMES ---
  { question: "What sandy biome generates Desert Temples and Wells?", answer: "Desert." },
  { question: "What biome features giant Mushroom Trees and no hostile mobs spawning naturally?", answer: "Mushroom Fields." },
  { question: "What dark underground biome contains Sculk Blocks and Ancient Cities?", answer: "Deep Dark." },
  { question: "What biome has pale gray trees, hanging moss, and Creaking mobs?", answer: "Pale Garden." },
  { question: "What swamp variant features Mangrove Trees and Mud blocks?", answer: "Mangrove Swamp." },
  { question: "What icy biome features towering ice spikes made of Packed Ice?", answer: "Ice Spikes." },
  { question: "What mountain biome is filled with Cherry Blossom trees and pink petals?", answer: "Cherry Grove." },
  { question: "What underground biome is filled with Moss, Spore Blossoms, and Dripleaf?", answer: "Lush Caves." },
  { question: "What structure generated in Trial Chambers contains spawner challenges?", answer: "Trial Spawner." },
  { question: "What underwater structure built from Prismarine contains Elder Guardians?", answer: "Ocean Monument." },
  { question: "What structure found in jungle biomes has puzzle levers and hidden chests?", answer: "Jungle Temple." },
  { question: "What sunken structure holds treasure maps and wood logs underwater?", answer: "Shipwreck." },
  { question: "What structure in Villages houses Cartographers and Librarians?", answer: "Village Houses." },
  { question: "What archaeological block can be swept with a Brush to reveal loot?", answer: "Suspicious Sand (or Suspicious Gravel)." },
  { question: "What block in Ancient Cities can trigger a Warden if stepped on quietly?", answer: "Sculk Sensor / Sculk Shrieker." },

  // --- TRIVIA, LORE & SOUNDS ---
  { question: "What item plays music when placed into a Jukebox?", answer: "Music Disc." },
  { question: "How many distinct Music Discs exist in Minecraft?", answer: "16+ Music Discs." },
  { question: "What rare music disc can only be obtained by getting a Skeleton to kill a Creeper?", answer: "Most standard Music Discs (e.g., Cat, Mellohi, Ward)." },
  { question: "What sound does a Creeper make right before exploding?", answer: "A burning fuse hiss ('Ssshhh...')." },
  { question: "What hostile mob mimics the sounds of nearby mobs to trick players?", answer: "Parrot." },
  { question: "What passive mob carries items given to it and collects more of the same item?", answer: "Allay." },
  { question: "What decorative head item can be obtained by killing a mob with a Charged Creeper?", answer: "Mob Head (Zombie, Skeleton, Creeper, Piglin)." },
  { question: "What creates a Charged Creeper?", answer: "A Creeper being struck by Lightning." },
  { question: "What painting depicts a skeleton holding a flaming skull?", answer: "Wither painting." },
  { question: "What status effect makes screens wobble and impairs visibility in ocean monuments?", answer: "Mining Fatigue." },

  // --- CRAFTING & UTILITY BLOCKS ---
  { question: "What block is used to rename items and combine enchantments?", answer: "Anvil." },
  { question: "What block removes enchantments from items and returns XP?", answer: "Grindstone." },
  { question: "What block cuts wood blocks into slabs and stairs precisely?", answer: "Stonecutter." },
  { question: "What block allows players to craft banner patterns and dye banners?", answer: "Loom." },
  { question: "What block cooks food twice as fast as a standard furnace?", answer: "Smoker." },
  { question: "What block smelts ores and metals twice as fast as a standard furnace?", answer: "Blast Furnace." },
  { question: "What block holds maps and allows players to zoom or clone them?", answer: "Cartography Table." },
  { question: "What block is used by Villagers to become Armorers?", answer: "Blast Furnace." },
  { question: "What block is used by Villagers to become Fletchers?", answer: "Fletching Table." },
  { question: "What block is used by Villagers to become Clerics?", answer: "Brewing Stand." },
  { question: "What decorative container holds up to 4 books on a stand?", answer: "Lectern." },
  { question: "What container item holds up to 64 items of various types in one inventory slot?", answer: "Bundle." },
  { question: "What decorative container retains its inventory items when broken and picked up?", answer: "Shulker Box." },
  { question: "What item is crafted with 1 Compass and 8 Paper?", answer: "Empty Map." },
  { question: "What block glows when powered and can project colored beacon lights into the sky?", answer: "Beacon." }

// --- MOB BEHAVIOR & DROPS ---
  { question: "What mob drops a Totem of Undying when defeated?", answer: "Evoker." },
  { question: "What mob summons Vexes to attack players?", answer: "Evoker." },
  { question: "What item do Sniffers dig up from Moss Blocks?", answer: "Torchflower Seeds and Pitcher Pods." },
  { question: "What item do Allays drop when given a new item to hold?", answer: "Whatever item they were originally holding." },
  { question: "What friendly mob can be bred using Armadillo Scutes or Spider Eyes?", answer: "Armadillo." },
  { question: "What item drops from Armadillos when brushed?", answer: "Armadillo Scute." },
  { question: "What item is crafted using Armadillo Scutes to protect pets?", answer: "Wolf Armor." },
  { question: "What passive mob floats down slowly and drops Slow Falling potion ingredients?", answer: "Phantom (Phantom Membrane)." },
  { question: "What mob spawns inside Trial Chambers and shoots wind charges?", answer: "Breeze." },
  { question: "What item is dropped by the Breeze and used to craft Wind Charges?", answer: "Breeze Rod." },
  { question: "What neutral mob transforms into a Witch when struck by lightning?", answer: "Villager." },
  { question: "What aquatic mob drops Scutes when growing from a baby to an adult?", answer: "Turtle." },
  { question: "What helmet item is crafted using 5 Turtle Scutes?", answer: "Turtle Shell." },
  { question: "What mob drops Glow Ink Sacs when defeated?", answer: "Glow Squid." },
  { question: "What mob drops Goat Horns when rammed into solid blocks?", answer: "Goat." },
  { question: "What neutral mob drops Leather and Rabbit Hide?", answer: "Rabbit." },
  { question: "How many Rabbit Hides are needed to craft 1 Leather?", answer: "4 Rabbit Hides." },
  { question: "What item does a Witch drop upon death?", answer: "Glass Bottles, Glowstone Dust, Redstone, Sticks, Sugar, or Potions." },
  { question: "What passive mob can carry a player across lava source blocks?", answer: "Strider." },
  { question: "What mob drops Shulker Shells used to craft storage boxes?", answer: "Shulker." },

  // --- OCEAN & WATER MECHANICS ---
  { question: "What structure in the ocean holds Heart of the Sea items in buried chests?", answer: "Shipwreck or Ocean Ruins." },
  { question: "What item combined with 8 Nautilus Shells creates a Conduit?", answer: "Heart of the Sea." },
  { question: "What underwater block structure activates a Conduit to grant powers?", answer: "Prismarine / Sea Lantern ring." },
  { question: "What status effect granted by Conduits lets you breathe and see underwater?", answer: "Conduit Power." },
  { question: "What happens to a Trident thrown into the air during a thunderstorm with Riptide?", answer: "It launches the player into the sky." },
  { question: "What coral item turns gray and dead when placed out of water?", answer: "Coral Blocks / Fan / Plant." },
  { question: "What block allows players to breathe underwater by creating air columns when placed under water?", answer: "Magma Block (downward column) or Soul Sand (upward column)." },
  { question: "What block creates upward bubble columns in water?", answer: "Soul Sand." },
  { question: "What block creates downward whirlpool bubble columns in water?", answer: "Magma Block." },
  { question: "What aquatic mob swims in schools and drops Tropical Fish items?", answer: "Tropical Fish." },

  // --- PLANTS, TREES & NATURE ---
  { question: "What flower variant grows in Dark Forest biomes and turns red dyes?", answer: "Poppy or Rose Bush." },
  { question: "What plant grows on Netherrack and glows orange-red in Crimson Forests?", answer: "Crimson Fungus." },
  { question: "What plant in Lush Caves hangs from the ceiling and drips water particles?", answer: "Spore Blossom." },
  { question: "What leaf block drops Cherries when broken?", answer: "Cherry Leaves (drops Saplings/Apples)." },
  { question: "What plant can be stepped on to bounce players into the air in Lush Caves?", answer: "Big Dripleaf." },
  { question: "What small plant closes and drops players when stood on for too long?", answer: "Big Dripleaf." },
  { question: "What item is harvested from Beehives using Shears?", answer: "Honeycomb." },
  { question: "What item is harvested from Beehives using Glass Bottles?", answer: "Honey Bottle." },
  { question: "What block prevents Bees from becoming angry when harvesting honey?", answer: "Campfire placed beneath the hive." },
  { question: "What crop plant yields Sugar and Paper?", answer: "Sugar Cane." },
  { question: "What plant grows on Sand in deserts and damages players who touch it?", answer: "Cactus." },
  { question: "What tree type produces Dark Oak Wood and requires 4 saplings in a 2x2 grid to grow?", answer: "Dark Oak Tree." },
  { question: "What tree type can grow into a 2x2 giant variant using 4 saplings?", answer: "Jungle / Spruce / Dark Oak." },
  { question: "What Nether plant can be climbed like ladders?", answer: "Weeping Vines (Crimson) or Twisting Vines (Warped)." },
  { question: "What vine grows UPWARDS in the Nether?", answer: "Twisting Vines." },

  // --- EXPLORATION & ADVANCEMENTS ---
  { question: "What item points toward the world spawn point by default?", answer: "Compass." },
  { question: "What item points toward a specific Lodestone block when right-clicked on it?", answer: "Lodestone Compass." },
  { question: "What rare structure is found buried in the Overworld using an Explorer Map from a Cartographer?", answer: "Ocean Monument or Woodland Mansion." },
  { question: "What item allows players to fly when combined with an Elytra?", answer: "Firework Rocket." },
  { question: "What advancement is unlocked by eating a Chorus Fruit?", answer: "Remote Teleportation." },
  { question: "What advancement is unlocked by hitting the exact center of a Target Block from 30 meters?", answer: "Bullseye." },
  { question: "What item is crafted using 8 Gold Ingots and 1 Apple?", answer: "Golden Apple." },
  { question: "What rare craftable item required 8 Gold BLOCKS and an Apple in older versions?", answer: "Enchanted Golden Apple (Notch Apple)." },
  { question: "What structure contains Vaults opened with Trial Keys?", answer: "Trial Chambers." },
  { question: "What key opens Ominous Vaults in Trial Chambers?", answer: "Ominous Trial Key." },

  // --- SPECIAL MECHANICS & TRIVIA ---
  { question: "What mob skin appears if a Cat is tamed on Christmas Eve/Day?", answer: "Santa Cat skin." },
  { question: "What item turns Wolf Armor into custom colors?", answer: "Dyes." },
  { question: "What item can color Leather Armor in a Cauldron?", answer: "Dyes mixed into water." },
  { question: "What item removes dye color from Leather Armor?", answer: "Water Cauldron." },
  { question: "What block holds lava without melting or catching fire?", answer: "Cauldron." },
  { question: "What item fills a Cauldron during rainstorms over time?", answer: "Water." },
  { question: "What item fills a Cauldron placed beneath Pointed Dripstone dripping lava?", answer: "Lava." },
  { question: "What cave block drips water or lava when placed under a source block?", answer: "Pointed Dripstone." },
  { question: "What status effect prevents players from breaking blocks at normal speed near Elder Guardians?", answer: "Mining Fatigue." },
  { question: "What item cures Mining Fatigue instantly?", answer: "Milk Bucket." },
  { question: "What item status effect gives night vision and highlights entities in white outlines?", answer: "Glowing (from Spectral Arrows)." },
  { question: "What arrow variant highlights targets through solid blocks when hit?", answer: "Spectral Arrow." },
  { question: "What item is crafted with 1 Arrow and 4 Glowstone Dust?", answer: "2 Spectral Arrows." },
  { question: "What item is crafted by combining a Book, Feather, and Ink Sac?", answer: "Book and Quill." },
  { question: "What block allows writing custom text that cannot be edited once signed?", answer: "Book and Quill (becomes Written Book)." },

  // --- VILLAGES & TRADING ---
  { question: "What villager profession uses a Loom as a job site block?", answer: "Shepherd." },
  { question: "What villager profession uses a Composter as a job site block?", answer: "Farmer." },
  { question: "What villager profession uses a Barrel as a job site block?", answer: "Fisherman." },
  { question: "What villager profession uses a Smithing Table as a job site block?", answer: "Toolsmith." },
  { question: "What villager profession uses a Grindstone as a job site block?", answer: "Weaponsmith." },
  { question: "What villager profession sells enchanted books?", answer: "Librarian." },
  { question: "What villager profession sells explorer maps to structures?", answer: "Cartographer." },
  { question: "What currency is used for trading with Villagers?", answer: "Emeralds." },
  { question: "What passive mob defends Villagers from hostile mobs?", answer: "Iron Golem." },
  { question: "How many Iron Blocks are required to build an Iron Golem?", answer: "4 Iron Blocks (and 1 Carved Pumpkin)." },
  { question: "What mob drops Emeralds and Saddles during Raids?", answer: "Ravager." },
  { question: "What item do Pillager Captains wear on their heads during patrols?", answer: "Ominous Banner." },
  { question: "What block rings to alert Villagers during a Raid?", answer: "Bell." },
  { question: "What trader spawns randomly near players with two Llamas?", answer: "Wandering Trader." },
  { question: "What item do Wandering Traders accept in exchange for rare goods?", answer: "Emeralds." },

  // --- CRAFTING & DECORATION ---
  { question: "What block is crafted using 4 Clay Balls?", answer: "Clay Block." },
  { question: "What block is created by baking a Clay Block in a Furnace?", answer: "Terracotta." },
  { question: "What block is crafted by baking Glazed Terracotta with dye?", answer: "Glazed Terracotta." },
  { question: "How many dye colors exist in Minecraft?", answer: "16 colors." },
  { question: "What item turns White Wool into Pink Wool directly?", answer: "Pink Dye." },
  { question: "What block is crafted using 8 Glass blocks and 1 Dye?", answer: "8 Stained Glass blocks." },
  { question: "What decorative block displays items inside a frame on walls?", answer: "Item Frame." },
  { question: "What item frame glows in the dark and is crafted with a Glow Ink Sac?", answer: "Glow Item Frame." },
  { question: "What item is crafted using 3 Sticks and 6 Wood Planks?", answer: "Fence Gate." },
  { question: "What item is crafted using 4 Wood Planks and 2 Sticks?", answer: "Fence." },
  { question: "What container holds items and can be attached to a Donkey or Mule?", answer: "Chest." },
  { question: "What vehicle floats on lava without burning when ridden by players?", answer: "Strider (with Saddle)." },
  { question: "What vehicle transports items along Rails automatically?", answer: "Minecart with Chest / Hopper." },
  { question: "What rail type powers Minecarts forward when powered by Redstone?", answer: "Powered Rail." },
  { question: "What rail type stops Minecarts when unpowered and acts as a brake?", answer: "Powered Rail." },

  // --- LIGHTING & DECORATIVE BLOCKS ---
  { question: "What underwater light source drops Prismarine Shards and Crystals?", answer: "Sea Lantern." },
  { question: "What light-emitting block is found hanging in Nether Fortresses?", answer: "Glowstone." },
  { question: "What light source is crafted with Iron Nuggies and a Torch?", answer: "Lantern." },
  { question: "What light source is crafted with Soul Soil, Iron Nuggets, and a Torch?", answer: "Soul Lantern." },
  { question: "What color flame does a Soul Torch or Soul Lantern emit?", answer: "Blue." },
  { question: "What light source block is crafted using 4 Amethyst Shards and a Copper Ingot?", answer: "Spyglass." },
  { question: "What tool allows players to zoom in on distant objects?", answer: "Spyglass." },
  { question: "What item is crafted with 1 Copper Ingot and 2 Amethyst Shards?", answer: "Spyglass." },
  { question: "What block attracts lightning strikes away from flammable wooden structures?", answer: "Lightning Rod." },
  { question: "What metal block oxidizes over time, changing from orange to green?", answer: "Copper Block." }
];
